import {test} from 'node:test';
import assert from 'node:assert/strict';
import {registerHooks} from 'node:module';
registerHooks({resolve(specifier,context,next){if(specifier.startsWith('.')&&!/\.[a-z]+$/i.test(specifier))return next(specifier+'.ts',context);return next(specifier,context);}});
const {restoreDatabaseBackup,prepareBackupRestore}=await import('../src/utils/databaseBackup.ts');
const {STORAGE_KEYS:K}=await import('../src/utils/storageKeys.ts');
const {APPOINTMENT_STOCK_KEY}=await import('../src/utils/appointmentStockStore.ts');
const backup={app:'DentisPro Dental Management System',patients:[],appointments:[{id:'a'}],inventory:[{id:'i',quantity:3}]};
function storage(initial={},fail=()=>false){const values=new Map(Object.entries(initial));return {values,getItem:k=>values.get(k)??null,setItem(k,v){if(fail(k,v))throw Error('quota');values.set(k,v);},removeItem:k=>values.delete(k)};}
test('restores canonical keys and the paired stock snapshot including templates',()=>{const s=storage();restoreDatabaseBackup(s,JSON.stringify({...backup,materialTemplates:{procedure:[{id:'r'}]},documentTemplates:[{id:'doc'}],savedClinicDocuments:[{id:'saved'}]}));assert.equal(s.getItem(K.PATIENTS),'[]');assert.equal(s.getItem('patients'),null);assert.equal(JSON.parse(s.getItem(APPOINTMENT_STOCK_KEY)).inventory[0].quantity,3);assert.deepEqual(JSON.parse(s.getItem(APPOINTMENT_STOCK_KEY)).materialTemplates,{procedure:[{id:'r'}]});assert.ok(s.getItem(K.DOCUMENT_TEMPLATES));assert.ok(s.getItem(K.SAVED_DOCUMENTS));});
test('ignores arbitrary session or localStorage keys',()=>{const s=storage({token:'keep'});restoreDatabaseBackup(s,JSON.stringify({...backup,token:'replace',dentispro_session:'evil'}));assert.equal(s.getItem('token'),'keep');assert.equal(s.getItem('dentispro_session'),null);});
test('rejects unrelated, incomplete or malformed backups before writing',()=>{for(const b of [{},{...backup,patients:null},{...backup,inventory:[null]},{...backup,appointments:[{id:'a'},{id:'a'}]},{...backup,materialTemplates:{p:{}}}]){const s=storage({sentinel:'keep'});assert.throws(()=>restoreDatabaseBackup(s,JSON.stringify(b)));assert.deepEqual([...s.values],[['sentinel','keep']]);}});
test('preserves documents absent from older backups and resets absent old stock templates',()=>{const s=storage({[K.SAVED_DOCUMENTS]:'[{"id":"old"}]'});restoreDatabaseBackup(s,JSON.stringify(backup));assert.equal(s.getItem(K.SAVED_DOCUMENTS),'[{"id":"old"}]');assert.deepEqual(JSON.parse(s.getItem(APPOINTMENT_STOCK_KEY)).materialTemplates,{});});
test('rolls back prior writes if a later write fails, including absent keys',()=>{const initial={[K.PATIENTS]:'[{"id":"old"}]',sentinel:'keep'};const s=storage(initial,k=>k===APPOINTMENT_STOCK_KEY);assert.throws(()=>restoreDatabaseBackup(s,JSON.stringify(backup)),/desfeitas/);assert.deepEqual(Object.fromEntries(s.values),initial);});
test('reports failure to roll back rather than claiming data was restored',()=>{let failed=false;const s=storage({[K.PATIENTS]:'old'},k=>{if(k===APPOINTMENT_STOCK_KEY){failed=true;return true;}return failed;});assert.throws(()=>restoreDatabaseBackup(s,JSON.stringify(backup)),/Pare de editar/);});
test('restores previously omitted supported fields',()=>{const writes=prepareBackupRestore(JSON.stringify({...backup,tussProcedures:[{code:'123'}],commissions:[{id:'c'}],insuranceGuides:[{id:'g'}],layoutTheme:'natural'}));for(const key of [K.TUSS_PROCEDURES,K.COMMISSIONS,K.INSURANCE_GUIDES,K.LAYOUT_THEME])assert.ok(writes.has(key));});
