export const STORAGE_KEYS = {
  PATIENTS: 'dentispro_patients_v2',
  APPOINTMENTS: 'dentispro_appointments_v2',
  INVENTORY: 'dentispro_inventory_v2',
  FINANCIAL: 'dentispro_financial_v2',
  PRESCRIPTIONS: 'dentispro_prescriptions_v2',
  ODONTOGRAMS: 'dentispro_odontograms_v2',
  ODONTOGRAM_SNAPSHOTS: 'dentispro_odontogram_snapshots_v2',
  EVOLUTIONS: 'dentispro_evolutions_v2',
  CLINICAL_EXAMS: 'dentispro_clinical_exams_v2',
  TREATMENT_PLANS: 'dentispro_treatment_plans_v2',
  PATIENT_PAYMENTS: 'dentispro_patient_payments_v2',
  TUSS_PROCEDURES: 'dentispro_tuss_procedures_v1',
  PRICE_TABLES: 'dentispro_price_tables_v1',
  CLINIC_INFO: 'dentispro_clinic_info_v1',
  CLINICS: 'dentispro_clinics_v1',
  PROFESSIONALS: 'dentispro_professionals_v1',
  ACTIVE_CLINIC: 'dentispro_active_clinic_v1',
  LAYOUT_THEME: 'dentispro_layout_theme_v1',
  COMMISSIONS: 'dentispro_commissions_v2',
  INSURANCE_GUIDES: 'dentispro_insurance_guides_v2',
  SAVED_DOCUMENTS: 'dentispro_saved_documents_v2',
  DOCUMENT_TEMPLATES: 'dentispro_document_templates_v1',
};
